#!/usr/bin/env python3
import asyncio
from tcp import Servidor
from tcp import Conexao
import re

# Define o atributo global dados_residuais para a classe Conexao
Conexao.dados_residuais = b''

# Define o atributo global nicks para a classe Conexao
_apelidos = {}

# Define o atributo global canais para a classe Conexao
_canais = {}

def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None


def sair(conexao):
    receptores_msg_sair = []
    # Procurar canais em que a conexão fechada está
    for canal in _canais:
        if conexao in _canais[canal]:
            # Adiciona canal em que a conexão fechada está na lista
            receptores_msg_sair += _canais[canal]
            # Remove a conexão do canal
            _canais[canal].pop(conexao)

    # Envia a mensagem de que o usuário saiu para usuários que estavam no mesmo canal
    for conexao_ in receptores_msg_sair:
        conexao_.enviar(b':%s QUIT :Connection closed\r\n' % _apelidos[conexao])

    # Verifica se o apelido está no dicionário
    if _apelidos.get(conexao) is not None:
        _apelidos.pop(conexao)
    
    #print(conexao, 'conexao fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    if dados == b'':
        return sair(conexao)
    
    # Concatena os dados residuais com os dados
    dados = Conexao.dados_residuais + dados
    
    # Cria uma lista para armazenar linhas terminadas em b'\r\n'
    linhas = dados.split(b'\r\n')

    # Se o último elemento da lista terminar com b'\r\n'
    if linhas[-1].endswith(b'\r\n'):
        # Caso não tenha dados residuais
        Conexao.dados_residuais = b''
    else:
        # Caso tenha dados residuais atribuí-lo a variável e removê-lo da lista
        Conexao.dados_residuais = linhas.pop(-1)

    for linha in linhas:
        #print(conexao, linha)
        processar_linha(conexao, linha)
    
def processar_linha(conexao, linha):
    # Remove espaços do começo e do final da string
    linha = linha.strip()
        
    ''' Verifica se as primeiras letras da linha é um comando
    indiferente de maiúsculas ou minúsculas. '''
    # PING
    if linha[0:4].upper() == b'PING':
        enviar_e_imprimir(conexao, b':server PONG server :%s\r\n' % linha.split()[1])
    # NICK
    elif linha[0:4].upper() == b'NICK':
        # Atribui a variável nome ao nick enviado
        nome = linha.split(b' ',1)[1]
        # Se nome for válido
        if validar_nome(nome):
            # Verifica se o dicionário está vazio
            nome_anterior = _apelidos.get(conexao)
            # Se estiver vazio atribui b'*' a variável nome_anterior
            if nome_anterior is None:
                nome_anterior = b'*'
            # Verifica se o nome já está em uso
            if nome.lower() in _apelidos.values():
                enviar_e_imprimir(conexao, b':server 433 %s %s :Nickname is already in use\r\n' % (nome_anterior, nome))
            # Se o nome não estiver em uso 
            elif nome_anterior == b'*':
                enviar_e_imprimir(conexao, b':server 001 %s :Welcome\r\n' % nome)
                enviar_e_imprimir(conexao, b':server 422 %s :MOTD File is missing\r\n' % nome)
                _apelidos[conexao] = nome.lower()
            # Trocar nome
            else:
                _apelidos[conexao] = nome.lower()
                enviar_e_imprimir(conexao, b':%s NICK %s\r\n' % (nome_anterior, nome))
        # Se nome for inválido
        else:
            enviar_e_imprimir(conexao, b':server 432 * %s :Erroneous nickname\r\n' % nome)
    # PRIVMSG
    elif linha[0:7].upper() == b'PRIVMSG':
        # Atribui o nome de quem envia a mensagem privada
        transmissor = _apelidos[conexao].lower()
        # Atribui o nome de quem vai receber a mensagem e a mensagem
        receptor, mensagem = linha.split()[1:]
        receptor = receptor.lower()
        # Mensagem para um canal
        if receptor.startswith(b'#'):
            # Remove o b'#'
            canal = receptor[1:]
            # Achar a conexao associada ao nome
            for c in _canais[canal]:
                # Não manda a mensagem para quem a enviou
                if(c != conexao):
                    # Envia mensagem
                    enviar_e_imprimir(c, b':%s PRIVMSG #%s %s\r\n' % (transmissor, canal, mensagem))
        # Mensagem privada para usuário
        elif receptor in _apelidos.values():
            # Achar a conexao associada ao nome
            for conexao, nome in _apelidos.items():
                if nome == receptor:
                    # Envia mensagem
                    enviar_e_imprimir(conexao, b':%s PRIVMSG %s %s\r\n' % (transmissor, receptor, mensagem))
    # JOIN
    elif linha[0:4].upper() == b'JOIN':
        canal = linha.split()[1][1:]
        if validar_nome(canal):
            # Cria o dicionário se ainda não existir
            if _canais.get(canal) is None:
                _canais[canal] = {}
            
            # Adiciona o apelido
            _canais[canal][conexao] = _apelidos[conexao]
            
            # Envia a mensagem de que usuário entrou no canal
            for conexao_ in _canais[canal]:
                # Não envia a mensagem para a própria pessoa que entrou no canal
                if (conexao_ != conexao):
                    conexao_.enviar(b':%s JOIN :#%s\r\n' % (_apelidos[conexao], canal))
            
            # Envia as mensagens de entrar e listar membros para o usuário que entrou no canal
            conexao.enviar(b':%s JOIN :#%s\r\n' % (_apelidos[conexao], canal) +
                        b':server 353 %s = #%s :' % (_apelidos[conexao], canal))

            # Cria uma string com os membros em ordem alfabética separados por b' '
            mensagem = b' '.join(sorted(_apelidos[conexao] for conexao in _canais[canal]))
            conexao.enviar(mensagem + b'\r\n')

            # Envia a mensagem de fim da lista de membros para quem usuário que entrou no canal
            conexao.enviar(b':server 366 %s #%s :End of /NAMES list.\r\n' % (_apelidos[conexao], canal))
        
            
            '''conexao.enviar(
                b':' + _apelidos[conexao] + b' JOIN :#' + canal + b'\r\n' +
                b':server 353 ' + _apelidos[conexao] + b' = #' + canal + b' :' +
                membros + b'\r\n' +
                b':server 366 ' + _apelidos[conexao]+b' #'+canal+b' :End of /NAMES list.\r\n')'''
        else:
            enviar_e_imprimir(conexao, b':server 403 %s :No such channel\r\n' % canal)
    # PART
    elif linha[0:4].upper() == b'PART':
        canal = linha.split()[1][1:]
        if validar_nome(canal):
            for c in _canais[canal]:
                enviar_e_imprimir(c, b':%s PART #%s\r\n' % (_apelidos[conexao], canal))
            _canais[canal].pop(conexao)
        else:
            enviar_e_imprimir(conexao, b':server 403 %s :No such channel\r\n' % canal)

def enviar_e_imprimir(conexao, dados):
    #print(dados)
    conexao.enviar(dados)
        
def conexao_aceita(conexao):
    #print(conexao, 'nova conexão')
    conexao.registrar_recebedor(dados_recebidos)

servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
